### PR TITLE
Update fakes3 to 1.0.0

### PR DESCRIPTION
**Pull request by zabawaba99**
https://rubygems.org/gems/fakes3/versions/1.0.0

### CODE REVIEW

**Comment by freeall** [comment]
ping @lphoward. It it possible to merge this? Ran into an issue with non-supported `ContentEncoding` which `fakes3` has fixed now so it'd be great to get this out 🥇

**Comment by freeall** [comment]
Heck, it could even be `1.2.0` which was released 5 days ago

**Comment by lphoward** [comment]
The concern I have is with the licensing change to fake-s3 beginning with 1.0.0.   I've been mulling it, but I'd really appreciate the thoughts of others.  How do you see the licensing change affecting the ways folks mostly use fake-s3?  How should this docker orchestration address concerns about the licensing change?

**Comment by freeall** [comment]
Hmm, I hadn't seen that, but it does look rather strange. I've never heard of "supported source" (which I think was then renamed to "super source") before. As far as I can see it's the people who made fake-s3 who made this. There's not that many projects using it either https://supso.org/projects

So I guess you aren't allowed to even use it without paying? Or how does that work? I have not seen any similar license for a project where the source is available before.

**Comment by freeall** [comment]
@lphoward I asked fakes3 about it, and I'm not getting a clear answer but it does indeed seem like you have to pay to use it (which I can't recall having seen before with any open source projects).

**Pull request closed without merging**
